import catalogue from "./catalogue.json";

/**
 * The real solar neighbourhood, as a source of conquest nodes.
 *
 * The catalogue is generated by `scripts/build-star-catalogue.mjs` from a
 * checked-in RECONS snapshot and committed, so nothing is fetched at runtime.
 * Binary and multiple systems are already merged there: Alpha Centauri A, B
 * and Proxima arrive here as one entry with three components.
 */

export interface CatalogueSystem {
  name: string;
  /** Light years from Sol. */
  distance: number;
  /** Equatorial Cartesian light years, Sol at the origin. */
  pos: number[];
  /** One spectral type per component, brightest first. */
  components: string[];
  /** Set on Sol alone, which always becomes the player capital. */
  home?: boolean;
}

/** Every catalogued system, ascending by distance, Sol first. */
export const STAR_SYSTEMS = catalogue.systems as CatalogueSystem[];

/** Provenance, shown wherever the mode explains where its data came from. */
export const CATALOGUE_SOURCE = catalogue.source;
export const CATALOGUE_EPOCH = catalogue.epoch;

/**
 * Radii offered by the wizard. Chosen so the resulting galaxies span roughly
 * 5 to 70 systems, which is the range the strategic map reads well at.
 */
export const RADIUS_CHOICES = [8, 10, 12, 14, 16, 19] as const;

/** Default radius, giving a mid-sized galaxy of a couple of dozen systems. */
export const DEFAULT_RADIUS_LY = 12;

/** Every system within `radiusLy` of Sol, Sol included. */
export function systemsWithin(radiusLy: number): CatalogueSystem[] {
  return STAR_SYSTEMS.filter((s) => s.distance <= radiusLy);
}

/** How many systems a radius yields, for the wizard's option labels. */
export function systemCountWithin(radiusLy: number): number {
  return systemsWithin(radiusLy).length;
}
